apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: single-container-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: single-container-app
    app.kubernetes.io/part-of: single-container-app
  name: single-container-app
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-container-app
      app.kubernetes.io/instance: single-container-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-container-app
        app.kubernetes.io/instance: single-container-app
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mkosiarc-tenant/single-container-app/single-container-app@sha256:771caad0948bab9ad807d76e3a278b44791c574f9aea75ec4b04b82e958d3ea7
        name: my-single-container
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
